apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guest-pv-claim
  labels:
    app: guest-mongo
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-mongo
  labels:
    app: guest-mongo
    tier: database
spec:
  selector:
    matchLabels:
      app: guest-mongo
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guest-mongo
        tier: database
    spec:
      containers:
        - name: mongo
          image: mongo:latest
#          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  key: username
#                  name: mongo-secret-guest
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  key: password
#                  name: mongo-secret-guest
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: guest-persistent-storage
              mountPath: /data/db
      volumes:
        - name: guest-persistent-storage
          persistentVolumeClaim:
            claimName: guest-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: guest-mongo
  labels:
    app: guest-mongo
    tier: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: guest-mongo
    tier: database
  clusterIP: None
