apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: guest-pv
  name: guest-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
