apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guest-app
  name: guest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guest-app
  strategy: {}
  template:
    metadata:
      labels:
#        io.kompose.network/kubernetes-config-default: "true"
        app: guest-app
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_DATABASE
              value: guest-info-db
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo-db-guest
            - name: SPRING_DATA_MONGODB_PORT
              value: "27018"
          image: matijamatovic/devops-guest-backend
          name: guest-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
